name: 'tools shared'
description: 'The tools shared action is used to support static checking capability'
inputs:
  checkers:  # name of checker
    description: 'What checker to use'
    required: true
    default: 'all'
  all:
    description: 'Is it necessary to conduct a full repository file check'
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Configure environment
      run: |
          python3 -m pip install requests PyYAML -i https://pypi.org/simple
          tools/hab sync
          source tools/envsetup.sh
      shell: bash
    - name: Run all check
      if: ${{ inputs.checkers == 'all' }} 
      run: |
          if [ ${{ inputs.all }} == 'true' ]; then
            git lynx check --all
          else
            git lynx check
          fi
      shell: bash
    - name: Run check
      if: ${{ inputs.checkers != 'all' }}
      run: |
        if [ ${{ inputs.all }} == 'true' ]; then
            git lynx check --checkers ${{ inputs.checkers }} --all
          else
            git lynx check --checkers ${{ inputs.checkers }}
          fi
      shell: bash
